// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY5-oQpXbQZaEViMqyvjFo4iEHilZjL2A',
    appId: '1:48253334540:web:7c529580cf65bf4df86a29',
    messagingSenderId: '48253334540',
    projectId: 'dotw-409a5',
    authDomain: 'dotw-409a5.firebaseapp.com',
    databaseURL: 'https://dotw-409a5-default-rtdb.firebaseio.com',
    storageBucket: 'dotw-409a5.appspot.com',
    measurementId: 'G-5G8KVMFJYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSU09aWAquJaSYwKLDD9EDSHF6h1qnhM',
    appId: '1:48253334540:android:ccac058c76247517f86a29',
    messagingSenderId: '48253334540',
    projectId: 'dotw-409a5',
    databaseURL: 'https://dotw-409a5-default-rtdb.firebaseio.com',
    storageBucket: 'dotw-409a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCcu1TOgJ7E-aiZyw_GZwAvliXmn6x3dU',
    appId: '1:48253334540:ios:b48890f11b65d1e0f86a29',
    messagingSenderId: '48253334540',
    projectId: 'dotw-409a5',
    databaseURL: 'https://dotw-409a5-default-rtdb.firebaseio.com',
    storageBucket: 'dotw-409a5.appspot.com',
    iosClientId: '48253334540-ss54bptjgmrba4bcl0c72hhrc5uai8c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dotw',
  );
}
